// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-MhbQkVxlrbeqCSGagiCnqAdPGaVL7U',
    appId: '1:227130848217:web:20eee43a599658bd63dfc8',
    messagingSenderId: '227130848217',
    projectId: 'codepie-b72a9',
    authDomain: 'codepie-b72a9.firebaseapp.com',
    storageBucket: 'codepie-b72a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBouEov18OxvuXqP9xCl57LRwEPaNM9Hx4',
    appId: '1:227130848217:android:e0f222888e8e6c3d63dfc8',
    messagingSenderId: '227130848217',
    projectId: 'codepie-b72a9',
    storageBucket: 'codepie-b72a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33Ynm4cofrg3ffmfbstG4F2Vpoq6lccY',
    appId: '1:227130848217:ios:70ce7f2d19a7394263dfc8',
    messagingSenderId: '227130848217',
    projectId: 'codepie-b72a9',
    storageBucket: 'codepie-b72a9.appspot.com',
    iosClientId: '227130848217-20udq2pf8ch0ab0pfc2g31arel7u1seb.apps.googleusercontent.com',
    iosBundleId: 'com.example.modelClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD33Ynm4cofrg3ffmfbstG4F2Vpoq6lccY',
    appId: '1:227130848217:ios:70ce7f2d19a7394263dfc8',
    messagingSenderId: '227130848217',
    projectId: 'codepie-b72a9',
    storageBucket: 'codepie-b72a9.appspot.com',
    iosClientId: '227130848217-20udq2pf8ch0ab0pfc2g31arel7u1seb.apps.googleusercontent.com',
    iosBundleId: 'com.example.modelClass',
  );
}
